### PR TITLE
Configuremiddleware

### PR DESCRIPTION
**Pull request by ghost**
This branch
Configures Middleware (server.js) for:
-Adding port that will enable exchange data exchange between services
-Configure static files for deployment to heroku

### CODE REVIEW

**Comment by ML-ex** [comment]
@AndrewIndeche Please resolve all the above violations and failing tests and let me know. 
Also, if you are stuck on anything let me know so we can unblock and move forward.  The point of this exercise is not to test/examine you rather for you to learn and adjust to a team environment. So I want to see your engagement on that end.

**Comment by ghost** [comment]
> @AndrewIndeche Please resolve all the above violations and failing tests and let me know. Also, if you are stuck on anything let me know so we can unblock and move forward. The point of this exercise is not to test/examine you rather for you to learn and adjust to a team environment. So I want to see your engagement on that end.

@ML-ex I am stuck at the hound errors displayed.I have added end of lines and some of the end of line errors are not resolving.Also is there any other way to reconfigure lint for es6 so that the syntax is recognized?

**Comment by ML-ex** [comment]
@AndrewIndeche Do you get this same errors on your VScode? Because from what I can see, the set up for ESLINT among other things is the issue... Can you please also share the links you used to set up the application,  because I am seeing a few unconventional things.  
Also, let me know when you are able to jump on a call so we can peer programme to resolve these issues

**Comment by ghost** [comment]
@ML-ex the test is passing locally and the errors do not show up on the vs code.

**Pull request closed without merging**
