### PR TITLE
Create levels

### PR DESCRIPTION
**Pull request by AndrewIMLEx**
This branch:
-Creates a new component called levels.
-Configures the game difficulty levels to standard or difficult.

### CODE REVIEW

**Comment by ML-ex** [comment]
The PR description on this PR seems to be the same for PR #29... does this mean they are doing the same thing?  Which one has the most recent changes?

**Comment by AndrewIMLEx** [comment]
> This branch: -Creates a new component called levels. -Configures the game difficulty levels to standard or difficult.

This branch is different from #29 I have adjusted the description

**Review by ML-ex — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts at the bottom of this PR and then reopen it. It seems you didn't remember to rebase the branch with the previous branch. After rebasing the branch do the same for the other PR and ping me on slack!

**Comment by ML-ex** [comment]
Resolve the conflicts locally and **NOT on the browser**.

**Comment by ML-ex** [comment]
Closing this PR because I believe it is outdated and all the changes are in the PR #33 that I just approved.

**Pull request closed without merging**
